---
version: "3.8"
services:
  movies:
    image: mulamwadpallavi/moviesrepo:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: mulamwadpallavi/trainrepo:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: mulamwadpallavi/rechargerepo:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: mulamwadpallavi/dthrepo:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
